/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function compress(data: string): Buffer | null
export function decompress(data: Buffer, originalSize: number): Buffer | null
export interface FileData {
  file: string
  hash: string
}
export function hashFile(file: string): FileData | null
export function hashFiles(workspaceRoot: string): Record<string, string>
